version: 2    
updates:
  - directory: /
    package-ecosystem: nuget
    ignore:
      - dependency-name: BepInEx.Core
      - dependency-name: HarmonyX
      - dependency-name: UnityEngine.Modules
    schedule:
      interval: daily
    target-branch: "develop"
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
    target-branch: "develop"
